### ISSUE TITLE
Support Custom Executor Artifacts

### ISSUE THREAD

**Issue by loicalbertin** [ystia/yorc#110]
As: An component designer / integrator
I want to: Define artifacts to add custom executors 
So that: I can easily extend Janus with my own TOSCA components

AC1: Synchronize with A4C team on this one!

Bellow is Luc's brain extract on custom executors artifacts:

```yaml
node_type:
  org.alien4cloud.think.nodes.ArtifactExecSample:
    derived_from: tosca.nodes.Root
    interfaces:
      lifecycle:
        operations:
          create:
            implementation: script.sh
            type: tosca.artifacts.Implementation.MyBash
            inputs:
              TOTO: get_property: {SELF, test}
          start:
            implementation: script.yml
            type: tosca.artifacts.Implementation.MyAnsible
  org.alien4cloud.think.nodes.HostedArtifactExecSample:
    derived_from: tosca.nodes.SoftwareComponent
    interfaces:
      lifecycle:
        operations:
          create:
            implementation: script.sh
            type: tosca.artifacts.Implementation.MyBash
          start:
            implementation: script.yml
            type: tosca.artifacts.Implementation.MyAnsible
 
 
artifact_types:
  tosca.artifacts.Implementation.MyBash:
    derived_from: tosca.artifacts.Implementation
    description: Ansible script my way artifact execution
    executor:
      from: tosca.artifacts.Implementation.Bash
      implementation:
        primary:
          shell_wrapper.sh
        dependencies:
          - utils.sh
          - other_utils.sh
  tosca.artifacts.Implementation.MyAnsible:
    derived_from: tosca.artifacts.Implementation
    description: Ansible script my way artifact execution
    executor:
      from: tosca.artifacts.Implementation.Bash
      implementation:
        primary:
          ans_wrapper.sh
        requirement:
          - execution_host:
              type: tosca.capabilites.AnsibleRuntime
              relationship: hosted_on # Hosted on means that artifact must be executed on the host that provide the capability
              # If not specified means that the artifact wrapper should be executed on the host of the component that holds the actual artifact
              # If the component does not have a host execute on an orchestrator sandbox
        supported_conn:
          protocol: ssh
          token_type: [password, ssh_key]
 
 
topology_tempalte:
  node_tempaltes:
    exec_sample_1:
      type: org.alien4cloud.think.nodes.ArtifactExecSample
      # execution of create operation (tosca.artifacts.Implementation.MyBash) should be on orchestrator sandbox
      # Orchestrator calls shell_wrapper.sh with inputs from node operation (TODO env variable, the expected operation JANUS_EXECUTION_HOST (none) TOSCA_PRIMARY_ARTIFACT with the path of the actual script to be wrapped, TOSCA_DEPENDENCIES_ARTIFACT )
 
      # start operation is ansible type and execution_host is provided by orchestrator:
      # Orchestrator should connect (as hosted on) on the machine and execute the artifact on the ansible machine
      # Orchestrator calls shell_wrapper.sh with inputs from node operation (TODO env variable, the expected operation TOSCA_EXECUTION_HOST (none) TOSCA_PRIMARY_ARTIFACT with the path of the actual script to be wrapped, TOSCA_DEPENDENCIES_ARTIFACT )
 
 
    compute:
      type: tosca.nodes.Compute
 
    exec_sample_2:
      type: org.alien4cloud.think.nodes.HostedArtifactExecSample:
      requirements:
        - host: compute
        # execution of create operation (tosca.artifacts.Implementation.MyBash) should be on the actual compute node instance
      # Orchestrator calls shell_wrapper.sh with inputs from node operation (TODO env variable, the expected operation TOSCA_EXECUTION_HOST=SELF TOSCA_PRIMARY_ARTIFACT with the path of the actual script to be wrapped, TOSCA_DEPENDENCIES_ARTIFACT )
 
            # start operation is ansible type and execution_host is provided by orchestrator:
      # Orchestrator should connect (as hosted on) on the machine and execute the artifact on the ansible machine
      # Orchestrator calls shell_wrapper.sh with inputs from node operation (TODO env variable, the expected operation TOSCA_EXECUTION_HOST=IP_OF_COMPUTE, TOSCA_EXECUTION_CREDENTIAL=tosca.datatypes.Credential of the admin endpoint of the compute,  TOSCA_PRIMARY_ARTIFACT with the path of the actual script to be wrapped, TOSCA_DEPENDENCIES_ARTIFACT )
 
 ```
