### ISSUE TITLE
Yorc consul service registration fails if using TLS

### ISSUE THREAD

**Issue by loicalbertin** [ystia/yorc#153]
# Issue Type

* [x] Bug report
* [ ] Documentation issue report
* [ ] Improvement request

## Description

When Yorc is configured to run in TLS then the registered TCP check in Consul fails

## Expected behavior

Consul service check should be OK

## Actual behavior

check fails

## Steps to reproduce the issue

1. [Configure Yorc to run in TLS](https://yorc.readthedocs.io/en/latest/secured.html#secured-yorc-setup)
2. Start Consul
3. start yorc

In Yorc logs:
```
sept. 03 15:32:40 lal-yorc yorc[9135]: 2018/09/03 15:32:40 http: TLS handshake error from [::1]:54538: EOF
sept. 03 15:32:45 lal-yorc yorc[9135]: 2018/09/03 15:32:45 http: TLS handshake error from [::1]:54540: EOF
sept. 03 15:32:50 lal-yorc yorc[9135]: 2018/09/03 15:32:50 http: TLS handshake error from [::1]:54544: EOF
sept. 03 15:32:55 lal-yorc yorc[9135]: 2018/09/03 15:32:55 http: TLS handshake error from [::1]:54546: EOF
sept. 03 15:33:00 lal-yorc yorc[9135]: 2018/09/03 15:33:00 http: TLS handshake error from [::1]:54548: EOF
```

In Consul logs
```
2018/09/03 15:34:50 [ERR] http: Request PUT /v1/session/create?dc=dc1, error: Check 'service:yorc' is in critical state from=127.0.0.1:44162
2018/09/03 15:34:52 [INFO] agent: Synced check "service:yorc"
```
## Yorc configuration file

```yaml
resources_prefix: lalyorc-
http_port: "8800"
server_id: "lal-yorc"
key_file: /etc/yorc/yorc-server.key
cert_file: /etc/yorc/yorc-server.pem
ca_file: /etc/yorc/ca.pem
ssl_verify: true
consul:
  address: "127.0.0.1:8500"
ansible:
  use_openssh: true

```
