### ISSUE TITLE
TOSCA Properties on relationships are not taken into account by Yorc

### ISSUE THREAD

**Issue by loicalbertin** [ystia/yorc#155]
# Issue Type

Put an X between the brackets of the corresponding issue type

* [x] Bug report
* [ ] Documentation issue report
* [ ] Improvement request

## Description

A `get_property: [SELF, propname]` on a relationship is not resolvable.

## Expected behavior

Should be resolved

## Actual behavior

Properties generated by Alien are not properly parsed as they do not respect the TOSCA spec.

Expected:
```
Compute:
  requirements:
    - local_storage:
        node: my_block_storage
        capability: tosca.capabilities.Attachment
        type_requirement: host
        relationship:
          type: tosca.relationships.AttachesTo
          properties:
            location: /dev/vde
```
Generated by Alien:
```
Compute:
  requirements:
    - local_storage:
        node: my_block_storage
        capability: tosca.capabilities.Attachment
        type_requirement: host
        relationship: tosca.relationships.AttachesTo
        properties:
          location: /dev/vde
```
