### ISSUE TITLE
Yorc bootstrap on 4.0.0-M7 doesn't work unless a download URL is provided for Yorc

### ISSUE THREAD

**Issue by loicalbertin** [ystia/yorc#561]
# Bug Report

## Description

When bootstrapping a yorc binary can't be downloaded.
Bellow is the ansible error

```yaml
[2019-12-02T05:59:35.219538866Z][ERROR][bootstrap-2019-12-02--05-54-41][install][c3d82f4c-44db-4268-aa3a-74bdd838542f][aa1210dc-2c1e-4368-8e1f-930dc18377f0-0][YorcServer][0][standard][create][]Ansible task output:
PLAY [Install Yorc] TASK [Download Yorc binary]
fatal: [10.0.0.216]: FAILED! => changed=false
  dest: /tmp/yorc.tgz
  invocation:
    module_args:
      attributes: null
      backup: null
      checksum: ''
      client_cert: null
      client_key: null
      content: null
      delimiter: null
      dest: /tmp/yorc.tgz
      directory_mode: null
      follow: false
      force: false
      force_basic_auth: false
      group: null
      headers: null
      http_agent: ansible-httpget
      mode: null
      owner: null
      regexp: null
      remote_src: null
      selevel: null
      serole: null
      setype: null
      seuser: null
      sha256sum: ''
      src: null
      timeout: 10
      tmp_dest: null
      unsafe_writes: null
      url: https://dl.bintray.com/ystia/yorc-engine/unknown/yorc-unknown.tgz
      url_password: null
      url_username: null
      use_proxy: true
      validate_certs: true
  msg: Request failed
  response: 'HTTP Error 404: Not Found'
  state: absent
  status_code: 404
  url: https://dl.bintray.com/ystia/yorc-engine/unknown/yorc-unknown.tgz
```

## Steps to reproduce the issue

1. Bootstrap yorc without a provided download url

## Output of `yorc version`

```bash
$ yorc version
Yorc Server 4.0.0-M7
Database schema version: 1.1.2
Revision: "78e4423cda51feee3c31564ffa443b2ba2c299fb"
```

## Priority

High
