### ISSUE TITLE
Failure running workflow with inline activity

### ISSUE THREAD

**Issue by laurentganne** [ystia/yorc#592]
# Bug Report

## Description

Attempting to run a workflow with an inline activity, like workflow wf2 below :
```yaml
    wf1:
      steps:
        Component_say_hello:
          target: Component
          activities:
            - call_operation: custom.say_hello
    wf2:
      steps:
        inline_wf1:
          activities:
            - inline: wf1
```

The execution of workflow wf2 is described to be successful, but  actually the inline workflow wf1 was not executed.
Yorc logs show this error :
```
[ERROR][yorc-example-Environment][wf2][78cfcf58-c218-49fb-94b3-fd173b140d5a][][][][][][]Failed to build step: "Component_say_hello" for workflow: "wf2", unknown step
[DEBUG][yorc-example-Environment][wf2][78cfcf58-c218-49fb-94b3-fd173b140d5a][][][][][][]Failed to build step: "Component_say_hello" for workflow: "wf2", unknown step
github.com/ystia/yorc/v4/tasks/workflow.(*worker).runWorkflowStep
        /home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/worker.go:777
github.com/ystia/yorc/v4/tasks/workflow.(*worker).runCustomWorkflow
        /home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/worker.go:748
github.com/ystia/yorc/v4/tasks/workflow.(*worker).handleExecution
        /home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/worker.go:220
github.com/ystia/yorc/v4/tasks/workflow.(*worker).Start.func1
        /home/travis/gopath/src/github.com/ystia/yorc/tasks/workflow/worker.go:83
runtime.goexit
```

## Output of `yorc version`

4.0.0-SNAPSHOT

## Priority

Medium

* High = We should stop anything we are doing and do this. If you're writing this calmly, you should probably choose another option. If it's really that urgent, please make sure we read this.
* Medium = It's important that we do this within a few days.
* Low = We will consider this on our next sprint planning.

(Please be aware that your priority may not match ours, we'll use this as guidance only).
