### ISSUE TITLE
Add the ability to define OpenStack Compute Instance user_data

### ISSUE THREAD

**Issue by laurentganne** [ystia/yorc#735]
The OpenStack API provides a Compute Instance property `user_data` allowing to provide configuration information or scripts used by cloud-init.

The TOSCA type `yorc.nodes.openstack.Compute` should be updated to support this user_data property, and the terraform provider should set this property described in [Terraform OpenStack provider documentation](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_instance_v2#user_data).

**Comment by loicalbertin** [comment]
Is  this related or unrelated to cloud-init?

**Comment by laurentganne** [comment]
> Is this related or unrelated to cloud-init?

yes, you can pass there cloud-init scripts. Example of user_data value that you can set and that will be used at cloud-init:
```
  #cloud-config
  write_files:
  - content: |
      /data/share *(rw,sync)
    owner: root:root
    path: /etc/exports
    permissions: '0644'
  runcmd:
   - [ mkdir, -p, /data/share ]
   - [ chown, "centos:centos", -R, /data/share ]
   - [ systemctl, enable, nfs-server ]
   - [ systemctl, start, nfs-server ]
   - [ exportfs, -avr ]
```
